backend:
  name: github
  repo: lntuandat/decapwebbanhang
  branch: master # Hoặc branch chính mà bạn sử dụng
  base_url: https://github.com
  auth_endpoint: /login/oauth/authorize
  app_id: Ov23li6DYEU120Wr0rSn


